[package]
name = "pfly_open_xplane"
version = "0.1.1"
authors = ["Skye Viau <skye.viau@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
xplm = "0.3.1"
pfly_rust = "0.1.1"
socket2 = "0.3.12"

[lib]
crate-type = ["cdylib"]
